sudo: required
services:
  - docker
language: generic
branches:
  only:
    - master
script:
  # Build and Test Ferret
  - git fetch --unshallow --tags
  - git describe --abbrev=0 --tags
  - make dummy
