sudo: required
services:
  - docker
language: generic
branches:
  only:
    - master
install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
script:
  # Build and Test Ferret
  - git fetch --unshallow --tags
  - git describe --abbrev=0 --tags
  - make dummy
