language: generic
git:
  depth: 1
before_install:
  - sudo apt-get update -qq
  - curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add -
script:
  - ls
  - ls
notifications:
  email:
    on_success: never
    on_failure: always
