language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      # I want to use this eventually, but right now it will prevent us
      # from installing g++-4.8 properly
      #- debian-sid
    packages:
      - g++-4.8
      #- libc++1
      #- libc++-dev
      #- libc++abi1
      #- libc++abi-dev
      - llvm-3.6-dev
      - clang-3.6

git:
  depth: 1
before_install:

script:
  - ls
  - clang++-3.6 test.cpp

