language: generic

apt:
 sources:
  - ubuntu-toolchain-r-test
  - llvm-toolchain-precise-3.6
 packages:
  - clang-3.6

git:
  depth: 1
before_install:
  - sudo apt-get update -qq
  - curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add -
script:
  - ls
  - clang++-3.6 test.cpp
notifications:
  email:
    on_success: never
    on_failure: always
