language: generic



git:
  depth: 1
before_install:
  - sudo apt-get update -qq
  - curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add -
  - echo "yes" | sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install clang-3.6
script:
  - ls
  - clang++-3.6 test.cpp
notifications:
  email:
    on_success: never
    on_failure: always
