language: generic
git:
  depth: 1
branches:
  only:
    - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-5
      - llvm-3.6-dev
      - clang-3.6
      - cppcheck
git:
  depth: 1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -qq -y build-dep emacs > /dev/null 2>&1
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
  # Install Emacs
  - wget -q http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.gz
  - tar xf emacs-24.5.tar.gz
  - cd emacs-24.5
  - ./configure > /dev/null 2>&1
  - make > /dev/null 2>&1
  - sudo make install > /dev/null 2>&1
  - cd ../
  # Install Clojure Toolchain
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod +x lein
  - sudo mv lein /usr/bin/
  - lein
script:
  - clang++-3.6 test.cpp

